<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>DeploymentAdditional</RootNamespace>
    <AssemblyName>DeploymentAdditional</AssemblyName>
    <StartupObject>DeploymentAdditional.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\notes.txt" />
  </ItemGroup>
</Project>